### ISSUE TITLE
1.9.1 version is broken?

### ISSUE THREAD

**Issue by wildcard** [kt3k/remarker#12]
```
npx --registry=https://registry.npmjs.org/ remarker -s webpagetest-meetup-slides.md

ENOENT: no such file or directory, open '/Users/kobi.kadosh/.npm/_npx/67802/lib/node_modules/remarker/assets/default.css'
Error: Name is not specified. you have to name your command by berber.name(name).
    at Berber.checkName (/Users/kobi.kadosh/.npm/_npx/67802/lib/node_modules/remarker/node_modules/berber/src/berber.js:20:13)
    at Promise.resolve.then (/Users/kobi.kadosh/.npm/_npx/67802/lib/node_modules/remarker/node_modules/berber/index.js:8:29)
```

**Comment by kt3k** [comment]
Thanks for pointing it. Sorry for inconvenience.

You are right. I introduced 'files' property in 1.9.1 ( https://github.com/kt3k/remarker/commit/68046a6972b29c01adc9e545b3eb9a9ccb4730de ) to avoid publishing unnecessary files, but it had some mistakes...

I fixed the problem and published it again. Please try v1.9.4.

**Comment by wildcard** [comment]
Thanks 🙏
